name: CI Pipeline
on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev


env:
  PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"
  SONAR_USER_HOME: "${{ github.workspace }}/.sonar"
  IMAGE_REGISTRY_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}
  DOCKER_TLS_CERTDIR: "/certs" # opcional

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    container:
      image: python:3.10-alpine
    env:
      PIP_CACHE_DIR: .cache/pip
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -V
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install flake8 pytest
      - run: |
          echo "====== Running lint ======"
          source .venv/bin/activate
          flake8
      - run: |
          echo "====== Running tests ======"
          source .venv/bin/activate
          pytest

  sonarcloud-check:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: lint-test
    container:
      image: sonarsource/sonar-scanner-cli:latest
      options: --entrypoint=""
    env:
      SONAR_USER_HOME: .sonar
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: .sonar/cache
          key: ${{ runner.os }}-sonar-${{ github.job }}
          restore-keys: |
            ${{ runner.os }}-sonar-
      - run: sonar-scanner -X

  bump:
    name: Bump version and tag
    runs-on: ubuntu-latest
    needs: sonarcloud-check
    container:
      image: python:3.10-slim
    env:
      GIT_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/cache@v4
        with:
          path: version
          key: ${{ runner.os }}-version-${{ github.sha }}
      - run: |
          apt-get update -qy && apt-get install -qqy openssh-client git
          mkdir -p ~/.ssh
          echo "${GIT_SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - run: |
          git config --global user.email "${GIT_USER_EMAIL}"
          git config --global user.name "${GIT_USER_NAME}"
      - run: pip install -U commitizen
      - run: |
          echo "====== Bumping version ======"
          cz bump --yes
      - run: |
          TAG=$(head -n 1 VERSION)
          echo "Pushing tag ${TAG}"
          git push origin HEAD:${{ github.ref_name }}
          git push origin ${TAG}
      - uses: actions/upload-artifact@v4
        with:
          name: version-file
          path: version

  build_dev:
    name: Build and Push Dev Image
    runs-on: ubuntu-latest
    needs: bump
    if: github.ref == 'refs/heads/dev'
    env:
      TAG: dev
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}
      - run: |
          touch .env-onboarding
          echo "=========== Building Homol image $IMAGE_REGISTRY_NAME:$TAG ==========="
          docker compose -f homol.yml build
          docker compose -f homol.yml push

  deploy_dev:
    name: Deploy Dev Environment
    runs-on: ubuntu-latest
    needs: build_dev
    if: github.ref == 'refs/heads/dev'
    env:
      TAG: dev
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      MACHINE_HOST_DEV: ${{ secrets.MACHINE_HOST_DEV }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update -qq && sudo apt-get install -qq openssh-client
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
      - run: |
          scp -o StrictHostKeyChecking=no conf.d/local.conf $MACHINE_HOST_DEV:~/conf.d/
          ssh -o StrictHostKeyChecking=no $MACHINE_HOST_DEV << 'EOF'
          sudo docker login ghcr.io --username=${DOCKER_USER} --password=${DOCKER_PASS}
          sudo docker pull ${IMAGE_REGISTRY_NAME}:${TAG}
          docker compose -f homol.yml stop
          sudo docker container prune -f
          docker compose -f homol.yml up -d
          EOF

  build_prod:
    name: Build & Push Production Image
    runs-on: ubuntu-latest
    needs: bump
    if: github.ref == 'refs/heads/main'
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: version-file
      - id: version
        run: echo "TAG=$(cat version)" >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}
      - run: |
          echo "=========== Building Prod image $IMAGE_REGISTRY_NAME:$TAG ==========="
          docker compose -f prod.yml build
          docker push $IMAGE_REGISTRY_NAME:$TAG

  deploy_main:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build_prod
    if: github.ref == 'refs/heads/main'
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      MACHINE_HOST_PROD: ${{ secrets.MACHINE_HOST_PROD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: version-file
      - id: version
        run: echo "TAG=$(cat version)" >> $GITHUB_ENV
      - run: sudo apt-get update -qq && sudo apt-get install -qq openssh-client
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
      - run: |
          scp -o StrictHostKeyChecking=no prod.yml $MACHINE_HOST_PROD:~/
          scp -o StrictHostKeyChecking=no conf.d/local.conf $MACHINE_HOST_PROD:~/conf.d/
          ssh -o StrictHostKeyChecking=no $MACHINE_HOST_PROD << 'EOF'
          sudo docker login ghcr.io --username=${DOCKER_USER} --password=${DOCKER_PASS}
          sudo docker pull ${IMAGE_REGISTRY_NAME}:${TAG}
          docker compose -f prod.yml stop
          sudo docker container prune -f
          docker compose -f prod.yml up -d
          EOF