/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    GenericTextInput: typeof import('./src/components/GenericTextInput.vue')['default']
    IconNav: typeof import('./src/components/icons/IconNav.vue')['default']
    NavGroup: typeof import('./src/components/sidenav/NavGroup.vue')['default']
    NavItem: typeof import('./src/components/sidenav/NavItem.vue')['default']
    NavMenu: typeof import('./src/components/sidenav/NavMenu.vue')['default']
    PButton: typeof import('./src/components/PButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
  }
}